Fix import bug for run_reports.sh . Remove unused imports.
Import bug:
  File "/opt/galaxy-central/lib/galaxy/webapps/reports/buildapp.py", line 25, in <module>
    class ReportsWebApplication( galaxy.web.framework.webapp.WebApplication ):
AttributeError: 'module' object has no attribute 'webapp'

The bug was introduced by commit 054438071ed9 .

--HG--
branch : stable


Former-commit-id: 01d9e9f1e6868cfeeb5797e155fbfa73e1b454fc