Rework checking binary files. Why read in line by line if only going to check 100 characters? This approach to just read first 100 characters is cleaner, more efficient, and hopefully less error prone. Should avoid the following exception caused when checking large files:
Traceback (most recent call last):
  File "/opt/galaxy/web/tools/data_source/upload.py", line 432, in <module>
    __main__()
  File "/opt/galaxy/web/tools/data_source/upload.py", line 421, in __main__
    add_file( dataset, registry, json_file, output_path )
  File "/opt/galaxy/web/tools/data_source/upload.py", line 283, in add_file
    if check_binary( dataset.path ):
  File "/opt/galaxy/web/lib/galaxy/datatypes/checkers.py", line 58, in check_binary
    for chars in temp:
SystemError: Negative size passed to PyString_FromStringAndSize

Former-commit-id: f1360c913f6f5f7e972edf387389cc363ab36fb9